name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.ROBERT_DOCKER_USERNAME }}
        password: ${{ secrets.ROBERT_DOCKER_PASSWORD }}
        repository: robertchenyf/software-engineer-final-team1-wordcloud
        tag_with_sha: true
