name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ROBERT_DOCKER_USERNAME }}
          password: ${{ secrets.ROBERT_DOCKER_PASSWORD }}
      -
        name: Build and push web app
        uses: docker/build-push-action@v3
        with:
          context: ./web-app
          push: true
          tags: robertchenyf/software-engineer-final-team1-wordcloud:web-latest
          
      -
        name: Build and push scraper app
        uses: docker/build-push-action@v3
        with:
          context: ./web-scraper
          push: true
          tags: robertchenyf/software-engineer-final-team1-wordcloud:scraper-latest
          
      - 
        name: Deploy to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          api_key: ${{ secrets.DIGITALOCEAN_API_KEY }}
          image: robertchenyf/software-engineer-final-team1-wordcloud:web-latest
          region: nyc1
          app_name: web
          environment: production
