name: web scraper workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  scrapertest:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./web-scraper
    timeout-minutes: 6
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.9']

    steps:
      - name: check out repo code
        uses: actions/checkout@v3
      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov
          pip install pytest-flask
      - name: execute unit tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
        run: |
        echo ${{ secrets.MONGO_URI }}
        pytest --cov